export const FETCH_REQUESTS_BEGIN = 'FETCH_REQUESTS_BEGIN'
export const FETCH_REQUESTS_SUCCESS = 'FETCH_REQUESTS_SUCCESS'
export const FETCH_REQUESTS_FAIL = 'FETCH_REQUESTS_FAIL'
export const FETCH_REQUESTS_CLEANUP = 'FETCH_REQUESTS_CLEANUP'


